-- drop old table if it exists.
DROP TABLE IF EXISTS saves;

-- create new table.
CREATE TABLE saves (
    name NVARCHAR(50) NOT NULL,
    password NVARCHAR(50) NOT NULL,
    gamestate NVARCHAR(MAX) NOT NULL,
    CONSTRAINT PK_saves PRIMARY KEY (name, password)
);

-- drop old table if it exists.
DROP TABLE IF EXISTS planets;

-- create new table.
CREATE TABLE planets (
    id INT PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    population INT NOT NULL
);

-- populate table with data.
INSERT INTO planets
(id, name, description, population)
VALUES
(0,'Romulus-Delta','A blue ocean planet. strange vessels glide over its surface.',4811304),
(1,'Cardassia-Phi','A merchant colony bustling with commerce.',3686586),
(2,'Balamb-9','A bleak & sparsely inhabited world.',335950),
(3,'Corel-1','A blue ocean planet. strange vessels glide over its surface.',3395960),
(4,'Cybertron-Xi','A small brutal planet where only the strong survive.',6121911),
(5,'Bleezor-Theta','An ancient planet inhabited by a powerful humanoid species.',7684875),
(6,'Luca-Gamma','A prison space station home to the worst of the worst.',3975146),
(7,'Lordran-Omega','A weapons research station shielded from prying eyes.',297455),
(8,'Cryon-Epsilon','A bleak & sparsely inhabited world.',341739),
(9,'Eleum-1','A travelling food ship that is famous for its Ramen bowls.',6613167),
(10,'Arda-Pi','A peaceful world inhabited by industrious people.',3502891),
(11,'Cybertron-Omicron','A weapons research station shielded from prying eyes.',1269800),
(12,'Nivion-Theta','A storm ravaged world where it always rains.',4946326),
(13,'Junon-9','The seat of power to a terrible empire.',9939030),
(14,'Djose-Kappa','A space ship graveyard inhabited by outlaws.',3541481),
(15,'Mideel-Upsilon','A merchant colony bustling with commerce.',1080656),
(16,'Gulug-Omega','A small space station situated near a black hole.',5065071),
(17,'Macalania-Alpha','The seat of power to a terrible empire.',9392532),
(18,'Silon-4','A mystical planet where beings with strange powers rule.',3498178),
(19,'Glaxon-Zeta','A storm ravaged world where it always rains.',6247900),
(20,'Halcyon-Rho','The ruined world of a once mighty civilization.',2858005),
(21,'Cleyra-Delta','A massive trading outpost. many species do business here.',5008797),
(22,'Corel-Tau','A peaceful planet with a highly religious population.',3265793),
(23,'Macalania-Lambda','A toxic planet whos people have long since fled.',3852108),
(24,'Romulus-Theta','A storm ravaged world where it always rains.',1594160),
(25,'Shulva-Epsilon','A dry planet where life exists without moisture.',2731694),
(26,'Corel-Alpha','The ruined world of a once mighty civilization.',9187583),
(27,'Terra-7','A small space station situated near a black hole.',6827234),
(28,'Cainhurst-Pi','A travelling food ship that is famous for its Ramen bowls.',5930952),
(29,'Iotov-Chi','A toxic planet whos people have long since fled.',7587289),
(30,'Djose-Alpha','The lush homeworld to a proud warrior race.',6020505),
(31,'Elea-Lambda','A mystical planet where beings with strange powers rule.',2032129),
(32,'Besaid-Xi','A lush forest planet brimming with wildlife.',1556166),
(33,'Arda-2','The lush homeworld to a proud warrior race.',6998250),
(34,'Alexandria-Eta','A gas giant surrounded by strange vessels.',2797492),
(35,'Balamb-Beta','A blue ocean planet. strange vessels glide over its surface.',1738770),
(36,'Izalith-Mu','A dry planet where life exists without moisture.',4086546),
(37,'Cardassia-8','A small space station situated near a black hole.',7712175),
(38,'Balamb-Omega','A cloning facility that raises armies for the highest bidders.',7345214),
(39,'Dali-Theta','The lush homeworld to a proud warrior race.',2785231),
(40,'Junon-Zeta','A blue ocean planet. strange vessels glide over its surface.',8640280),
(41,'Eleum-Xi','A derelict alien vessel drifting through space.',7471165),
(42,'Macalania-Pi','A technologically advanced world where energy is currency.',2588411),
(43,'Iotov-Kappa','A blue ocean planet. strange vessels glide over its surface.',8969957),
(44,'Gongaga-Delta','A peaceful world inhabited by industrious people.',8649349),
(45,'Romulus-Upsilon','A peaceful planet with a highly religious population.',7269625),
(46,'Elea-Chi','A small space station situated near a black hole.',2633202),
(47,'Cleyra-Tau','A derelict alien vessel drifting through space.',1467639),
(48,'Gongaga-Delta','A prison space station home to the worst of the worst.',1708873),
(49,'Oolacile-7','The lush homeworld to a proud warrior race.',8942797),
(50,'Talaxia-Eta','A bustling mining planet rich with natural resources.',3421293),
(51,'Nivion-9','A technologically advanced world where energy is currency.',8519828),
(52,'Nivion-9','A frozen tundra planet. blizzards rage continuously.',2228053),
(53,'Erd-9','A mysterious planet whos inhabitants have long died.',2601159),
(54,'Bleezor-Psi','A dark & noxious planet. deadly spores blanket its surface.',7685677),
(55,'Junon-Chi','The seat of power to a terrible empire.',6409251),
(56,'Bruma-Nu','A densely populated planet where everything is scarce.',3114178),
(57,'Talaxia-Kappa','A dark & noxious planet. deadly spores blanket its surface.',3087335),
(58,'Krypton-Chi','A blue ocean planet. strange vessels glide over its surface.',7909394),
(59,'Burmecia-Nu','A mystical planet where beings with strange powers rule.',8911296),
(60,'Talara-Rho','A derelict alien vessel drifting through space.',9904897),
(61,'Wutai-6','A peaceful planet with a highly religious population.',1236951),
(62,'Zanarkand-8','A storm ravaged world where it always rains.',123358),
(63,'Guadosalam-Eta','A technologically advanced world where energy is currency.',869582),
(64,'Eleum-3','A prison space station home to the worst of the worst.',3751457),
(65,'Eleum-Mu','A prison space station home to the worst of the worst.',4786450),
(66,'Nivion-Theta','A peaceful planet with a highly religious population.',8803700),
(67,'Krypton-Beta','A dark & noxious planet. deadly spores blanket its surface.',561418),
(68,'Mora-3','A lush forest planet brimming with wildlife.',7617397),
(69,'Izalith-Kappa','A merchant colony bustling with commerce.',8066761),
(70,'Guadosalam-Gamma','A bleak & sparsely inhabited world.',4027650),
(71,'Iotov-Kappa','A prison space station home to the worst of the worst.',8849923),
(72,'Cardassia-Beta','An aquatic planet. research stations lie below its waves.',1107718),
(73,'Romulus-Epsilon','A quaint space station known for delicious food.',5419690),
(74,'Drangleic-Gamma','A peaceful planet with a highly religious population.',2070341),
(75,'Talara-5','A dark & noxious planet. deadly spores blanket its surface.',981735),
(76,'Kilika-Zeta','An aquatic planet. research stations lie below its waves.',3063096),
(77,'Luca-Psi','A toxic planet whos people have long since fled.',4649909),
(78,'Mideel-Phi','An ancient planet inhabited by a powerful humanoid species.',931430),
(79,'Oolacile-1','A space ship graveyard inhabited by outlaws.',3714253),
(80,'Shulva-Kappa','A densely populated planet where everything is scarce.',6868161),
(81,'Izalith-6','The ruined world of a once mighty civilization.',1125558),
(82,'Macalania-Sigma','A dry planet where life exists without moisture.',4902209),
(83,'Cryon-Mu','A tropical planet where many species seem to vacation.',2186630),
(84,'Gongaga-Nu','The lush homeworld to a proud warrior race.',3554752),
(85,'Corel-Kappa','The lush homeworld to a proud warrior race.',5908241),
(86,'Romulus-Zeta','A densely populated planet where everything is scarce.',2119143),
(87,'Drangleic-2','A lush forest planet brimming with wildlife.',2440368),
(88,'Macalania-Nu','A technologically advanced world where energy is currency.',3844817),
(89,'Burmecia-Upsilon','An abandoned mining colony thats now home to space pirates.',2970607),
(90,'Gongaga-Xi','A quaint space station known for delicious food.',8691592),
(91,'Mideel-Psi','A small space station situated near a black hole.',6605192),
(92,'Shulva-Zeta','A bleak & sparsely inhabited world.',1076995),
(93,'Iotov-7','A quaint space station known for delicious food.',2255549),
(94,'Kepler-Eta','A small brutal planet where only the strong survive.',1736373),
(95,'Halcyon-Nu','A beautiful tropical planet brimming with life.',1378533),
(96,'Erus-Alpha','A frozen tundra planet. blizzards rage continuously.',9017282),
(97,'Shulva-Gamma','The ruined world of a once mighty civilization.',544634),
(98,'Corel-Tau','A massive trading outpost. many species do business here.',2758629),
(99,'Arda-Omicron','A dark & noxious planet. deadly spores blanket its surface.',2513887),
(100,'Kilika-Delta','A space ship graveyard inhabited by outlaws.',4036440),
(101,'Izalith-Omega','A tropical planet where many species seem to vacation.',9100492),
(102,'Macalania-Rho','An ancient planet inhabited by a powerful humanoid species.',7612878),
(103,'Erus-Iota','A small brutal planet where only the strong survive.',5693076),
(104,'Treno-Epsilon','A tropical planet where many species seem to vacation.',6701147),
(105,'Nivion-Eta','A beautiful tropical planet brimming with life.',2598080),
(106,'Gongaga-Delta','A small brutal planet where only the strong survive.',6057969),
(107,'Wutai-9','A world that fell to catastophic climate change.',9336855),
(108,'Talara-1','A lush forest planet brimming with wildlife.',8410168),
(109,'Erd-2','The ruined world of a once mighty civilization.',2044007),
(110,'Wutai-Chi','A mystical planet where beings with strange powers rule.',5022421),
(111,'Corel-6','A derelict alien vessel drifting through space.',3617880),
(112,'Junon-Rho','A bustling mining planet rich with natural resources.',9359531),
(113,'Terra-Sigma','A mystical planet where beings with strange powers rule.',6247713),
(114,'Gulug-Lambda','A dry planet where life exists without moisture.',4406123),
(115,'Besaid-Tau','A storm ravaged world where it always rains.',5225809),
(116,'Luca-Phi','A dry planet where life exists without moisture.',4849795),
(117,'Mora-Mu','A gas giant surrounded by strange vessels.',5074913),
(118,'Treno-Sigma','A small space station situated near a black hole.',6611520),
(119,'Silon-Beta','A tropical planet where many species seem to vacation.',2048180),
(120,'Erd-Eta','A quaint space station known for delicious food.',2791929),
(121,'Gallifrey-Rho','A dark & noxious planet. deadly spores blanket its surface.',9559752),
(122,'Macalania-Iota','A bustling mining planet rich with natural resources.',1519007),
(123,'Gulug-Omega','A peaceful world inhabited by industrious people.',3503187),
(124,'Gongaga-2','A space ship graveyard inhabited by outlaws.',92167),
(125,'Mideel-9','The ruined world of a once mighty civilization.',7640310),
(126,'Gallifrey-Phi','A dry planet where life exists without moisture.',6034261),
(127,'Doth-Theta','A blue ocean planet. strange vessels glide over its surface.',3722637),
(128,'Arda-6','A small brutal planet where only the strong survive.',4325696),
(129,'Bleezor-Rho','A storm ravaged world where it always rains.',6852988),
(130,'Gongaga-6','A mystical planet where beings with strange powers rule.',8000523),
(131,'Gulug-Beta','A peaceful planet with a highly religious population.',4463262),
(132,'Wutai-Omega','A dark & noxious planet. deadly spores blanket its surface.',848396),
(133,'Erus-Theta','A world that fell to catastophic climate change.',3276845),
(134,'Talara-Omicron','A quaint space station known for delicious food.',3856647),
(135,'Bleezor-2','A bustling mining planet rich with natural resources.',2738585),
(136,'Kilika-Upsilon','An ancient planet inhabited by a powerful humanoid species.',3559477),
(137,'Talara-Upsilon','A small brutal planet where only the strong survive.',155467),
(138,'Glaxon-6','A weapons research station shielded from prying eyes.',3321661),
(139,'Talara-Zeta','A toxic planet whos people have long since fled.',8110081),
(140,'Junon-Rho','A ruined wartorn planet. civil war has raged for generations.',5594343),
(141,'Balamb-Eta','A prison space station home to the worst of the worst.',9106274),
(142,'Bevelle-Omicron','A gas giant surrounded by strange vessels.',412200),
(143,'Zanarkand-Xi','A space ship graveyard inhabited by outlaws.',8074196),
(144,'Burmecia-Eta','The seat of power to a terrible empire.',4983741),
(145,'Alexandria-Mu','A technologically advanced world where energy is currency.',4321354),
(146,'Alexandria-Tau','A dark & noxious planet. deadly spores blanket its surface.',3659268),
(147,'Gulug-Zeta','A mystical planet where beings with strange powers rule.',9700356),
(148,'Mideel-Phi','A small space station situated near a black hole.',1591348),
(149,'Kilika-6','The lush homeworld to a proud warrior race.',4916593),
(150,'Djose-Kappa','A derelict alien vessel drifting through space.',3336722),
(151,'Eleum-Phi','The seat of power to a terrible empire.',4134102),
(152,'Treno-Beta','A mysterious planet whos inhabitants have long died.',8517120),
(153,'Cardassia-Beta','A technologically advanced world where energy is currency.',3050492),
(154,'Iotov-7','A lush forest planet brimming with wildlife.',6873050),
(155,'Alexandria-Kappa','A storm ravaged world where it always rains.',8811241),
(156,'Yharnam-Theta','A toxic planet whos people have long since fled.',6284802),
(157,'Eleum-Beta','A beautiful tropical planet brimming with life.',3169685),
(158,'Cryon-Psi','A weapons research station shielded from prying eyes.',6010123),
(159,'Lordran-Sigma','A quaint space station known for delicious food.',3556285),
(160,'Halcyon-1','An ancient planet inhabited by a powerful humanoid species.',1427060),
(161,'Wutai-Kappa','A travelling food ship that is famous for its Ramen bowls.',572816),
(162,'Doth-7','A volcanic planet. much of its surface is covered by magma.',8026793),
(163,'Mideel-4','A weapons research station shielded from prying eyes.',7935845),
(164,'Nivion-5','A cloning facility that raises armies for the highest bidders.',297182),
(165,'Alexandria-Omicron','A peaceful planet with a highly religious population.',9907595),
(166,'Zanarkand-Upsilon','A travelling food ship that is famous for its Ramen bowls.',4293720),
(167,'Halcyon-Iota','A mysterious planet whos inhabitants have long died.',3983871),
(168,'Bevelle-1','A ruined wartorn planet. civil war has raged for generations.',5363026),
(169,'Macalania-Tau','A peaceful world inhabited by industrious people.',4183894),
(170,'Mora-4','A blue ocean planet. strange vessels glide over its surface.',1388396),
(171,'Yharnam-3','A ruined wartorn planet. civil war has raged for generations.',9720366),
(172,'Mora-Gamma','A merchant colony bustling with commerce.',3686198),
(173,'Corel-Mu','An ancient planet inhabited by a powerful humanoid species.',2787669),
(174,'Cardassia-4','A peaceful planet with a highly religious population.',7971874),
(175,'Talaxia-4','An aquatic planet. research stations lie below its waves.',8146978),
(176,'Yharnam-Rho','A volcanic planet. much of its surface is covered by magma.',6069812),
(177,'Kilika-4','A peaceful world inhabited by industrious people.',9343482),
(178,'Glaxon-Delta','A storm ravaged world where it always rains.',311091),
(179,'Macalania-2','A storm ravaged world where it always rains.',7421613),
(180,'Nivion-9','A merchant colony bustling with commerce.',2661333),
(181,'Talaxia-Rho','The seat of power to a terrible empire.',6416460),
(182,'Luca-Phi','A bustling mining planet rich with natural resources.',1046098),
(183,'Junon-Theta','A frozen tundra planet. blizzards rage continuously.',7694388),
(184,'Alexandria-Iota','A quaint space station known for delicious food.',8421504),
(185,'Djose-3','A lush forest planet brimming with wildlife.',4669135),
(186,'Bleezor-Tau','A blue ocean planet. strange vessels glide over its surface.',8473633),
(187,'Izalith-Omicron','A cloning facility that raises armies for the highest bidders.',6818971),
(188,'Midgar-Theta','A prison space station home to the worst of the worst.',8961959),
(189,'Gongaga-4','A dark & noxious planet. deadly spores blanket its surface.',8210122),
(190,'Cainhurst-Mu','A bustling mining planet rich with natural resources.',2900042),
(191,'Gallifrey-Upsilon','The seat of power to a terrible empire.',9773941),
(192,'Nuna-Alpha','A densely populated planet where everything is scarce.',7292553),
(193,'Talaxia-Eta','A tropical planet where many species seem to vacation.',5662590),
(194,'Talara-Psi','A peaceful planet with a highly religious population.',1587792),
(195,'Wutai-Epsilon','A mystical planet where beings with strange powers rule.',37658),
(196,'Arda-Lambda','An abandoned mining colony thats now home to space pirates.',7082846),
(197,'Elea-Lambda','A technologically advanced world where energy is currency.',6583604),
(198,'Bruma-Xi','A mystical planet where beings with strange powers rule.',6959797),
(199,'Cainhurst-Upsilon','A world that fell to catastophic climate change.',8525699),
(200,'Kepler-Eta','An ancient planet inhabited by a powerful humanoid species.',6875480);
-- populate table with data.

-- drop old table if it exists.
DROP TABLE IF EXISTS aliens;

-- create new table.
CREATE TABLE aliens (
    id INT PRIMARY KEY,
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    health INT NOT NULL,
    armor INT NOT NULL,
    money INT NOT NULL
);

-- populate table with data.
INSERT INTO aliens
(id, name, description, health, armor, money)
VALUES
(0,'Dusk Cosmos','A cyborg more machine than person. She is ruthless and efficient.',10,3,412),
(1,'Adelbert God of Sunlight','A humanoid fighter from another dimension.',12,3,222),
(2,'Odo The Rock','A proud father and fierce protector of the planet.',12,3,328),
(3,'Snarf Coral','A fox starship pilot known for his bravery.',10,2,373),
(4,'Kira Alexandros','A strange dark creature. it wields powerful magic.',11,1,485),
(5,'Cloud Crescent','A strange dark creature. it wields powerful magic.',10,3,318),
(6,'SHODAN Carol','A fox starship pilot known for his bravery.',10,3,183),
(7,'Cloud Heartilly','The Father of Sunlight. he has sacrificed everything for power.',11,2,255),
(8,'Spock Lockhart','A twisted monster and the father of an unstoppable abyss.',9,3,181),
(9,'Mewtwo Purple','A flufy yellow creature that produces lightning when angry.',13,2,261),
(10,'Miles Nerys','An ancient horror. Revered by many as a God.',12,2,271),
(11,'Spock Carol','A young girl and the last of her once powerful race.',13,1,440),
(12,'Barret Wallace','An ancient horror. Revered by many as a God.',12,3,447),
(13,'Seven Thundercat','A proud father and fierce protector of the planet.',9,3,330),
(14,'Seven Ketchum','A humanoid officer. Cold logical and highly intelligent.',9,3,187),
(15,'Sif Wallace','A humanoid fighter from another dimension.',9,1,217),
(16,'Artorias Cosmos','The Father of Sunlight. he has sacrificed everything for power.',9,2,362),
(17,'Marth Branford','A young girl and the last of her once powerful race.',12,2,239),
(18,'Celes Heartilly','The last of her kind. Hunted by many.',13,3,455),
(19,'Tifa of Catarina','A humanoid fighter from another dimension.',9,2,172),
(20,'Yuffie Alexandros','A legendary humanoid warrior. Known for facing impossible odds.',9,3,310),
(21,'Beatrix of Astora','A cyborg more machine than person. She is ruthless and efficient.',9,3,100),
(22,'Tifa Tribal','A test subject who can now transform into monstrous beasts.',10,3,422),
(23,'Spock Valentine','An ancient horror. Revered by many as a God.',10,1,327),
(24,'Barret of Oolacile','A humanoid officer. Cold logical and highly intelligent.',9,3,205),
(25,'Yuffie Purple','The personal knight to her king. Her strength has no equal.',11,1,479),
(26,'Thanos Prower','A fox starship pilot known for his bravery.',9,1,322),
(27,'Solaire XIII','A legendary humanoid warrior. Known for facing impossible odds.',9,3,206),
(28,'Amygdala Branford','An ancient horror. Revered by many as a God.',10,1,204),
(29,'Artorias Strife','A young mercenary bearing a large scar across his face.',12,2,144),
(30,'Leon Sith','A cyborg more machine than person. She is ruthless and efficient.',11,1,176),
(31,'Mewtwo of Catarina','A skilled thief who will do anything for the right price.',10,3,475),
(32,'Megatron Chere','A fox starship pilot known for his bravery.',13,1,302),
(33,'Seven Synthesis','A proud father and fierce protector of the planet.',13,3,162),
(34,'Rinoa Sith','A really cool guy.',9,1,292),
(35,'Gandalf Steiner','A mechanical zealot bent on domination at all costs.',12,2,173),
(36,'Siegward The Rock','A strange dark creature. it wields powerful magic.',12,1,386),
(37,'Spock Horror','A humanoid officer. Cold logical and highly intelligent.',13,1,155),
(38,'Garnet Heartilly','A small fury creature with a bag of mail over its shoulder.',10,2,311),
(39,'Tuvok Branford','A young girl and the last of her once powerful race.',12,3,334),
(40,'Eiko Valentine','A cat-like humanoid. Proud and strong; They will not falter.',12,1,393),
(41,'Tuvok Ketchum','A formidable dragoon knight wielding a ceremonial lance.',13,3,262),
(42,'Knuckles of Catarina','A giant black dragon. It has devoured countless souls.',12,1,103),
(43,'Rinoa Heartilly','A mechanical zealot bent on domination at all costs.',13,3,373),
(44,'Terra Ketchum','A strange dark creature. it wields powerful magic.',13,1,361),
(45,'Zidane the Hedgehog','A young girl and the last of her once powerful race.',11,3,271),
(46,'Kira Autobot','A humanoid clad in heavy stone plates. His defenses are legendary.',11,2,124),
(47,'Vivi Wallace','A humanoid fighter from another dimension.',11,3,270),
(48,'Gwyn Sith','A humanoid terrorist leader who rejects all authority but her own.',12,1,405),
(49,'Mewtwo Purple','A strange dark creature. it wields powerful magic.',13,2,102),
(50,'Jenova the White','A powerful warrior bent on achieving Godhood.',12,3,165),
(51,'Kuja Horror','A proud father and fierce protector of the planet.',9,2,246),
(52,'Kirby Carol','A small pudgy thing. it insults you mercilessly.',10,3,199),
(53,'Manus Decepticon','A plump humanoid who values honor (and beer) above all else.',10,2,128),
(54,'Ebrietas Father of Abyss','A formidable dragoon knight wielding a ceremonial lance.',12,3,371),
(55,'SHODAN Laren','An ace pilot with a foul mouth and a nicotine addiction.',13,2,322),
(56,'Liono Crescent','A scorned giant with many eyes and arms. It delights in torture.',13,1,333),
(57,'Manus Chere','A humanoid terrorist leader who rejects all authority but her own.',12,3,476),
(58,'Squall Valentine','The son of noble warrior.',11,2,274),
(59,'Marth Thundercat','An omnipotent AI. It will stop at nothing to impose its will.',10,3,438),
(60,'Red McCloud','A terrible evil. Ancients called it The Calamity From the Skies.',11,2,309),
(61,'Amygdala Purple','A pretty young woman accompanied by her dog.',9,2,399),
(62,'Beatrix Decepticon','A giant black dragon. It has devoured countless souls.',13,2,395),
(63,'Amygdala Horror','A skilled thief who will do anything for the right price.',10,2,203),
(64,'Gwyn Ornitier','The personal knight to her king. Her strength has no equal.',12,1,187),
(65,'Barret the Echidna','A humanoid clad in heavy stone plates. His defenses are legendary.',13,2,291),
(66,'Moogle the Grey','A flufy yellow creature that produces lightning when angry.',12,1,125),
(67,'Vincent Laren','A young girl and the last of her once powerful race.',9,3,489),
(68,'Squall Decepticon','A formidable dragoon knight wielding a ceremonial lance.',13,1,498),
(69,'Zell the Hedgehog','A shape shifter capable of fantastic feats when transformed.',12,1,372),
(70,'Artorias Highwind','A humanoid martial artist known for her beauty and strength.',10,1,198),
(71,'Red Carol','A humanoid clad in heavy stone plates. His defenses are legendary.',9,2,194),
(72,'Sif of Astora','A skilled thief who will do anything for the right price.',13,2,468),
(73,'Knuckles the Echidna','A shape shifter capable of fantastic feats when transformed.',11,2,475),
(74,'Mewtwo the Echidna','A princess pulled away from her own space and time.',11,2,350),
(75,'Mewtwo Crescent','An impulsive humanoid fighter known for his quick temper.',10,1,348),
(76,'Liono God of Sunlight','The son of noble warrior.',12,2,127),
(77,'Celes Purple','A cyborg more machine than person. She is ruthless and efficient.',12,3,325),
(78,'Liono Ornitier','A proud father and fierce protector of the planet.',11,2,385),
(79,'Gwyn XIII','A small pudgy thing. it insults you mercilessly.',13,2,164),
(80,'Gandalf Sith','A powerful humanoid ancient whos power knows no bounds.',9,3,151),
(81,'Pikachu Purple','A terrible evil. Ancients called it The Calamity From the Skies.',12,3,104),
(82,'Vincent Cosmos','An omnipotent AI. It will stop at nothing to impose its will.',13,2,217),
(83,'Amarant Greatwolf','An impulsive humanoid fighter known for his quick temper.',13,2,396),
(84,'Amarant Wallace','A twisted monster and the father of an unstoppable abyss.',9,2,149),
(85,'Siegward Father of Abyss','A young mercenary bearing a large scar across his face.',9,1,325),
(86,'Moogle Alexandros','A young mercenary bearing a large scar across his face.',10,1,268),
(87,'SHODAN Greatwolf','A formidable dragoon knight wielding a ceremonial lance.',10,1,433),
(88,'Freya Purple','A humanoid clad in heavy stone plates. His defenses are legendary.',10,3,380),
(89,'Adelbert Heartilly','A fox starship pilot known for his bravery.',12,3,295),
(90,'Vincent Coral','A test subject who can now transform into monstrous beasts.',12,1,331),
(91,'Zell Synthesis','A fox starship pilot known for his bravery.',9,3,105),
(92,'Zell Purple','The personal knight to her king. Her strength has no equal.',11,2,430),
(93,'Red Greatwolf','A scorned giant with many eyes and arms. It delights in torture.',9,3,102),
(94,'Jenova Steiner','A large humanoid driven mad and bent on destruction.',12,1,316),
(95,'Eiko Synthesis','An ace pilot with a foul mouth and a nicotine addiction.',11,3,353),
(96,'Megatron Laren','A noble knight who would give his life for his princess.',12,1,286),
(97,'Sif Heartilly','A plump humanoid who values honor (and beer) above all else.',10,3,393),
(98,'Tuvok Nerys','A pretty young woman accompanied by her dog.',10,2,366),
(99,'Leon the Dragonslayer','A skilled thief who will do anything for the right price.',13,1,300),
(100,'Artorias Chere','A large humanoid robot. A steadfast protecter of its kind.',11,2,489),
(101,'Starscream Coral','A humanoid clad in heavy stone plates. His defenses are legendary.',13,1,309),
(102,'Sephiroth Branford','A giant black dragon. It has devoured countless souls.',11,3,163),
(103,'Marth Dincht','A humanoid martial artist known for her beauty and strength.',9,2,422),
(104,'Leon One Winged Angel','An ancient horror. Revered by many as a God.',9,3,392),
(105,'Rinoa of Catarina','A powerful warrior bent on achieving Godhood.',12,1,193),
(106,'Knuckles the White','A plump humanoid who values honor (and beer) above all else.',10,3,289),
(107,'Amarant Lockhart','A princess who fled her kingdom to seek adventure.',13,2,200),
(108,'Celes Lionheart','A powerful warrior bent on achieving Godhood.',13,2,220),
(109,'Solaire Carol','A humanoid terrorist leader who rejects all authority but her own.',11,2,498),
(110,'Zell Strife','A large humanoid robot. A steadfast protecter of its kind.',11,1,108),
(111,'Ebrietas Tribal','A flufy yellow creature that produces lightning when angry.',12,2,381),
(112,'Thanos XIII','A massive wolf-like creature. It will die before it surrenders.',12,1,500),
(113,'Miles Smith','An ace pilot with a foul mouth and a nicotine addiction.',12,1,249),
(114,'Tuvok Coral','A cat-like humanoid. Proud and strong; They will not falter.',10,1,415),
(115,'SHODAN Tribal','A small pudgy thing. it insults you mercilessly.',11,1,367),
(116,'Rinoa of Astora','A small pudgy thing. it insults you mercilessly.',12,3,159),
(117,'Amygdala the Abysswalker','A leader to his people. His wisdom is known across the galaxy.',13,3,281),
(118,'Liono Carol','A humanoid freedom fighter from an occupied world.',11,1,418),
(119,'Manus the Dragon','The last of her kind. Hunted by many.',10,3,199),
(120,'Kira Carol','The humanoid captain of his lords knights. A fierce dragon slayer.',12,3,268),
(121,'Odo of Astora','A terrible evil. Ancients called it The Calamity From the Skies.',9,3,387),
(122,'Odo the Abysswalker','An omnipotent AI. It will stop at nothing to impose its will.',13,2,467),
(123,'Kalameet Laren','A scorned giant with many eyes and arms. It delights in torture.',13,1,466),
(124,'Squall Valentine','A fox starship pilot known for his bravery.',10,3,358),
(125,'Marth of Catarina','A small pudgy thing. it insults you mercilessly.',9,3,498),
(126,'Eiko Coral','A young girl and the last of her once powerful race.',12,2,461),
(127,'Rinoa Ketchum','The humanoid captain of his lords knights. A fierce dragon slayer.',12,1,499),
(128,'Dusk the Echidna','A large humanoid robot. A steadfast protecter of its kind.',10,3,333),
(129,'Liono Ketchum','An impulsive humanoid fighter known for his quick temper.',12,3,157),
(130,'Gandalf Valentine','A large humanoid driven mad and bent on destruction.',9,1,315),
(131,'Adelbert Wallace','A leader to his people. His wisdom is known across the galaxy.',12,1,158),
(132,'Siegward the Dragonslayer','A skilled thief who will do anything for the right price.',10,3,196),
(133,'Vincent Autobot','A test subject who can now transform into monstrous beasts.',9,3,491),
(134,'Mog Kupo','A cat-like humanoid. Proud and strong; They will not falter.',12,1,166),
(135,'Ro Laren','The Father of Sunlight. he has sacrificed everything for power.',12,2,263),
(136,'Mewtwo Smith','A terrible evil. Ancients called it The Calamity From the Skies.',12,1,210),
(137,'Manus Greatwolf','An ancient horror. Revered by many as a God.',10,3,410),
(138,'Tifa Cosmos','A small fury creature with a bag of mail over its shoulder.',9,2,494),
(139,'Roger the Abysswalker','A humanoid martial artist known for her beauty and strength.',9,3,304),
(140,'Leon Valentine','A really cool guy.',12,2,107),
(141,'Ro Carol','The last of her kind. Hunted by many.',12,2,335),
(142,'Garnet Horror','The personal knight to her king. Her strength has no equal.',9,2,325),
(143,'Kuja Purple','An omnipotent AI. It will stop at nothing to impose its will.',10,3,404),
(144,'Squall Steiner','The personal knight to her king. Her strength has no equal.',12,2,172),
(145,'Starscream Synthesis','An ancient horror. Revered by many as a God.',12,2,198),
(146,'Kirby the Hedgehog','The Father of Sunlight. he has sacrificed everything for power.',12,2,439),
(147,'Pikachu God of Sunlight','A proud father and fierce protector of the planet.',9,2,278),
(148,'Siegward Carol','A test subject who can now transform into monstrous beasts.',11,2,230),
(149,'Marth of Catarina','A giant black dragon. It has devoured countless souls.',13,1,140),
(150,'Moogle Laren','A legendary humanoid warrior. Known for facing impossible odds.',9,2,465),
(151,'Megatron Ketchum','A noble knight who would give his life for his princess.',10,3,219),
(152,'Zidane XIII','A shape shifter capable of fantastic feats when transformed.',9,1,390),
(153,'Miles the Grey','A terrible evil. Ancients called it The Calamity From the Skies.',13,1,305),
(154,'Gwyn Thundercat','The son of noble warrior.',12,1,205),
(155,'Terra the Abysswalker','A flufy yellow creature that produces lightning when angry.',11,3,422),
(156,'Tuvok of Astora','A small furry creaure. It frequently repeats its own name.',11,2,292),
(157,'Zell Coral','A powerful warrior bent on achieving Godhood.',13,1,140),
(158,'Ebrietas One Winged Angel','The personal knight to her king. Her strength has no equal.',10,2,315),
(159,'Mog Lionheart','The son of noble warrior.',12,1,320),
(160,'Vivi the Grey','A leader to his people. His wisdom is known across the galaxy.',13,1,432),
(161,'Beatrix Kupo','A humanoid martial artist known for her beauty and strength.',10,3,422),
(162,'Odo the White','A proud father and fierce protector of the planet.',10,3,367),
(163,'Amarant the Abysswalker','The personal knight to her king. Her strength has no equal.',12,1,190),
(164,'Manus the Abysswalker','A large humanoid robot. A steadfast protecter of its kind.',12,3,139),
(165,'Knuckles Carol','A massive wolf-like creature. It will die before it surrenders.',13,3,118),
(166,'Ro Heartilly','A mechanical zealot bent on domination at all costs.',9,3,417),
(167,'Seven Chere','A large humanoid driven mad and bent on destruction.',9,2,441),
(168,'Adelbert XIII','A powerful warrior bent on achieving Godhood.',12,3,250),
(169,'Sonic the Echidna','A terrible evil. Ancients called it The Calamity From the Skies.',11,3,263),
(170,'Megatron Alexandros','A shape shifter capable of fantastic feats when transformed.',12,3,226),
(171,'Solaire Greatwolf','A terrible evil. Ancients called it The Calamity From the Skies.',13,3,224),
(172,'Vincent Ornitier','A noble knight who would give his life for his princess.',12,1,495),
(173,'Artorias Smith','A legendary humanoid warrior. Known for facing impossible odds.',10,2,116),
(174,'Kira McCloud','A mechanical zealot bent on domination at all costs.',11,1,409),
(175,'Rinoa The Rock','A humanoid clad in heavy stone plates. His defenses are legendary.',13,3,456),
(176,'Marth XIII','A really cool guy.',13,3,443),
(177,'Tuvok the Echidna','A scorned giant with many eyes and arms. It delights in torture.',13,1,391),
(178,'Celes Greatwolf','A fox starship pilot known for his bravery.',12,3,480),
(179,'Optimus Cosmos','A formidable dragoon knight wielding a ceremonial lance.',10,3,259),
(180,'Celes Lockhart','An omnipotent AI. It will stop at nothing to impose its will.',11,1,472),
(181,'Amygdala Sith','A scorned giant with many eyes and arms. It delights in torture.',11,3,356),
(182,'Cloud Thundercat','A completely normal gambling robot.',11,1,455),
(183,'Optimus the Grey','A terrible evil. Ancients called it The Calamity From the Skies.',10,2,149),
(184,'Yuffie Prower','A mechanical zealot bent on domination at all costs.',13,1,468),
(185,'Miles Valentine','A pretty young woman accompanied by her dog.',12,2,266),
(186,'Barret Decepticon','The personal knight to her king. Her strength has no equal.',13,1,428),
(187,'Megatron Tribal','An impulsive humanoid fighter known for his quick temper.',12,1,402),
(188,'Artorias of Astora','A proud father and fierce protector of the planet.',13,3,269),
(189,'Havel Autobot','A young girl and the last of her once powerful race.',13,2,484),
(190,'Odo Highwind','A humanoid fighter from another dimension.',9,2,132),
(191,'Sephiroth Kupo','A massive wolf-like creature. It will die before it surrenders.',10,1,393),
(192,'Beatrix of Catarina','The Father of Sunlight. he has sacrificed everything for power.',11,2,339),
(193,'Leon Horror','A powerful humanoid ancient whos power knows no bounds.',12,3,274),
(194,'Tuvok the Hedgehog','A massive wolf-like creature. It will die before it surrenders.',9,1,348),
(195,'Kirby Smith','An impulsive humanoid fighter known for his quick temper.',11,3,269),
(196,'Kira the Dragonslayer','A completely normal gambling robot.',13,1,265),
(197,'Mewtwo the Echidna','A mechanical zealot bent on domination at all costs.',12,1,107),
(198,'Pikachu Prower','A mechanical zealot bent on domination at all costs.',9,1,349),
(199,'Spock McCloud','A giant black dragon. It has devoured countless souls.',10,3,160),
(200,'Kirby Lockhart','A princess pulled away from her own space and time.',13,1,329);

-- drop old table if it exists.
DROP TABLE IF EXISTS items;

-- create new table.
CREATE TABLE items (
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    price int NOT NULL,
	quest bit NOT NULL
);

-- populate table with data.
INSERT INTO items
(name,description,price,quest)
VALUES
('Vision Goggles','To see in dark areas.',5,0),
('Safety Ropes','For saftey.',3,0),
('Pocket knives','For emergencies.',2,0),
('Safety Gloves','To protect hans.',2.5,0),
('Rusty Coin','An old coin with no value.',10,0),
('Childs Doll','A doll that reminds you of home.',15,0),
('Old Ring','A simple ring tarnished by time.',20,1),
('Strange Key','A key to an unknown lock.',30,1);
-- populate table with data.

-- drop old table if it exists.
DROP TABLE IF EXISTS potion;

-- create new table.
CREATE TABLE potion (
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    price int NOT NULL,
	quest bit NOT NULL,
	healthEffect int NOT NULL,
	damageEffect int NOT NULL
);

-- populate table with data.
INSERT INTO potion
(name,description,price,quest, healthEffect,damageEffect)
VALUES
('Kryptonite','Glowing green potion that invigorates you.',150,0,5,8),
('Health Potion','A bright red potion that revitalizes you.',350,0,10,15);
-- populate table with data.

-- drop old table if it exists.
DROP TABLE IF EXISTS treasure;

-- create new table.
CREATE TABLE treasure (
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    price int NOT NULL,
	quest BIT NOT NULL,
);

-- populate table with data.
INSERT INTO treasure
(name,description,price,quest)
VALUES
('Silver Star','A valuable star made of pure silver.',100,0),
('Black Star','A valuable star made of pure titanium.',150,0),
('Iron Cross','A cross made of iron.',200,0),
('Ancient Jewel','A beautiful gemstone from an ancient world.',250,0),
('Warp Drive','A single use warp drive that can take you to another galaxy. Use with [WARP].',9999,1);
-- populate table with data.

-- drop old table if it exists.
DROP TABLE IF EXISTS weapons;

-- create new table.
CREATE TABLE weapons (
    name NVARCHAR(50) NOT NULL,
    description NVARCHAR(MAX) NOT NULL,
    price int NOT NULL,
	quest bit NOT NULL,
	damageType NVARCHAR(50) NOT NULL,
	amtOfDamage int NOT NULL
);

-- populate table with data.
INSERT INTO weapons
(name,description,price,quest, damageType, amtOfDamage)
VALUES
('Phaser','A handheldpersonal defense weapon.',100,0,'elemental',2),
('Pulse Cannon','A large cannon that fires a tetryon pulse.',200,0,'projectile',4),
('Disruptor','A powerful weapon capable of destroying hulls.',300,0,'disintegrate',6),
('Assault Rifle','A rifle capable of automatic fire.',400,0,'rifle',7),
('Moonlight Greatsword','A legendary sword. Its massive blade can fire waves of moonlight.',500,0,'sword',8),
('Bat''leth','A long curved blade with several handles. Favored by warriors.',600,0,'blade',9),
('Anduril','A lost sword of legend. Reforged and made whole.',700,0,'impale',10),
('Tonitrus','A mace with a dynamo inside. swings produce powerful lightning strikes.',800,0,'chemcial',11),
('Flamethrower','A device that drowns enemies in flames.',250,0,'fire',3),
('Powergloves','heavy gauntlets for pummeling your enemies.',350,0,'heavyduty',5),
('Crystal Staff','A magical staff with a large mass of crystals on the end.',750,0,'crystal',12),
('Dragonslayer Swordspear','A massive swordspear imbued with lightning. Designed to kill dragons.',950,0,'swordspear',15);
-- populate table with data.
